import {
	VALUE_TYPE_ANY,
	VALUE_TYPE_BOOLEAN,
	VALUE_TYPE_DOUBLE,
	VALUE_TYPE_GEO_POINT,
	VALUE_TYPE_INSTANT,
	VALUE_TYPE_LOCAL_DATE,
	VALUE_TYPE_LOCAL_DATE_TIME,
	VALUE_TYPE_LOCAL_TIME,
	VALUE_TYPE_LONG,
	VALUE_TYPE_REFERENCE,
	VALUE_TYPE_SET,
	VALUE_TYPE_STRING,
} from '@enonic/js-utils/storage/indexing/valueType/constants';

const BOOLEAN_PROPS = [
	'active', // TODO: From GUI
	'enabled',
	'fulltext',
	'includeInAllText',
	'nGram',
	'path',
	'stemmed'
];
Object.freeze(BOOLEAN_PROPS);

const POSITIVE_INTEGER_PROPS = ['max', 'min'];
Object.freeze(POSITIVE_INTEGER_PROPS);

const ALLOWED_PROPS = BOOLEAN_PROPS.concat(
	POSITIVE_INTEGER_PROPS,
	['name', 'valueType']
);
Object.freeze(ALLOWED_PROPS);

const VALUE_TYPES = [
	VALUE_TYPE_ANY,
	VALUE_TYPE_BOOLEAN,
	VALUE_TYPE_DOUBLE,
	VALUE_TYPE_GEO_POINT,
	VALUE_TYPE_INSTANT,
	VALUE_TYPE_LOCAL_DATE,
	VALUE_TYPE_LOCAL_DATE_TIME,
	VALUE_TYPE_LOCAL_TIME,
	VALUE_TYPE_LONG,
	VALUE_TYPE_REFERENCE,
	VALUE_TYPE_SET,
	VALUE_TYPE_STRING
];
Object.freeze(VALUE_TYPES);

export {
	ALLOWED_PROPS,
	BOOLEAN_PROPS,
	POSITIVE_INTEGER_PROPS,
	VALUE_TYPES,
}
